name: Send all issues to a project

on:
  issues:
    types: [opened]

jobs:
  send-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Add issue to project
        uses: actions/add-to-project@v3
        with:
          project-slug: MT-EN-BO-v1
          column-name: 🆕 New
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
